spring:
  security:
    oauth2:
      client:
        provider:
          github:
            user-name-attribute: login
        registration:
          github-idp:
            provider: github
            client-id: ${jack.oauth2.github.client-id:your id}
            client-secret: ${jack.oauth2.github.client-secret:your secret}
            scope:
              - user:email
              - read:user
            client-name: Github sign in